# Generated by Django 5.0.7 on 2026-07-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('plot_size', models.CharField(max_length=100)),
                ('constrution_start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('construction_end_date', models.DateField()),
                ('project_status', models.CharField(max_length=100)),
                ('estimated_cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='devhome',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
