# Generated by Django 5.0.7 on 2026-07-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_alter_devhome_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='username',
            new_name='user_id',
        ),
    ]
