# Generated by Django 5.0.7 on 2026-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_username_project_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='construction_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
