# Generated by Django 6.0.6 on 2026-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_expenses_alter_devhome_id_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='for_what',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
