# Generated by Django 6.0.6 on 2026-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_expenses_for_what'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('labour_name', models.CharField(max_length=100)),
                ('contractor_name', models.CharField(max_length=100)),
                ('working_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
